name: Build Images

on:
  push:
    branches:
      - master

jobs:
  build-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: login docker
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u wangsijie --password-stdin
      - name: build hub
        run: docker build -t wangsijie/code-server-hub .
      - name: push
        run: docker push wangsijie/code-server-hub
